# Generated by Django 4.2.30 on 2026-07-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_crmintegration_crmsynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmintegration',
            name='project_mapping_source',
            field=models.CharField(choices=[('custom_field', 'Custom field'), ('identifier', 'Project identifier')], default='custom_field', max_length=20),
        ),
    ]
