# Generated by Django 4.2.30 on 2026-07-22 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_crmintegration_project_mapping_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmTaskLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('crm_task_id', models.PositiveIntegerField()),
                ('crm_project_id', models.PositiveIntegerField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_task_link', to='db.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_task_links', to='db.workspace')),
            ],
            options={
                'verbose_name': 'CRM Task Link',
                'verbose_name_plural': 'CRM Task Links',
                'db_table': 'crm_task_links',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CrmTimerLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('crm_timer_id', models.PositiveIntegerField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('worklog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_timer_link', to='db.issueworklog')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_timer_links', to='db.workspace')),
            ],
            options={
                'verbose_name': 'CRM Timer Link',
                'verbose_name_plural': 'CRM Timer Links',
                'db_table': 'crm_timer_links',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='crmintegration',
            name='crm_invoice_hours_field_id',
        ),
        migrations.RemoveField(
            model_name='crmintegration',
            name='last_sync_status',
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='crm_staff_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CrmSyncLog',
        ),
    ]
