# Generated by Django 4.2.30 on 2026-08-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
        ('db', '0129_crm_realtime_sync'),
    ]

    operations = [
    ]
