# Generated by Django 5.2.15 on 2026-09-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_merge_20260811_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmintegration',
            name='timer_webhook_secret_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
