# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

from .base import HrWorkspaceConfigEndpoint
from .billing import (
    HrInvoiceAcceptVarianceEndpoint,
    HrInvoiceEndpoint,
    HrInvoiceReconcileEndpoint,
    HrRateCardEndpoint,
    HrStatementEndpoint,
)
from .master_data import (
    HrAbsenceTypeEndpoint,
    HrCandidateEndpoint,
    HrContractEndpoint,
    HrEmploymentProfileEndpoint,
    HrHolidayCalendarEndpoint,
    HrHolidayEndpoint,
    HrLeaveEntitlementEndpoint,
    HrWorkScheduleEndpoint,
    HrSetupEndpoint,
)
from .period import (
    HrMeEndpoint,
    HrOverviewEndpoint,
    HrPeriodApproveEndpoint,
    HrPeriodDaySettleEndpoint,
    HrPeriodDaysEndpoint,
    HrPeriodDetailEndpoint,
    HrPeriodListEndpoint,
    HrPeriodLockEndpoint,
    HrPeriodRecomputeEndpoint,
    HrWorklogDetailEndpoint,
    HrPeriodReopenEndpoint,
    HrPeriodSubmitEndpoint,
)
from .transfer import (
    HrImportCommitEndpoint,
    HrImportEndpoint,
    HrImportUndoEndpoint,
    HrMonthExportEndpoint,
    HrOpeningBalanceAcknowledgeEndpoint,
    HrOpeningBalanceEndpoint,
    HrPeriodExportEndpoint,
)
from .records import (
    HrAbsenceCalendarEndpoint,
    HrAbsenceDecisionEndpoint,
    HrAbsenceEndpoint,
    HrAttendanceDayEndpoint,
    HrTimeEntryEndpoint,
)

__all__ = [
    "HrAbsenceCalendarEndpoint",
    "HrAbsenceDecisionEndpoint",
    "HrAbsenceEndpoint",
    "HrAbsenceTypeEndpoint",
    "HrCandidateEndpoint",
    "HrContractEndpoint",
    "HrEmploymentProfileEndpoint",
    "HrHolidayCalendarEndpoint",
    "HrHolidayEndpoint",
    "HrImportCommitEndpoint",
    "HrImportEndpoint",
    "HrImportUndoEndpoint",
    "HrInvoiceAcceptVarianceEndpoint",
    "HrInvoiceEndpoint",
    "HrInvoiceReconcileEndpoint",
    "HrLeaveEntitlementEndpoint",
    "HrMeEndpoint",
    "HrMonthExportEndpoint",
    "HrOpeningBalanceAcknowledgeEndpoint",
    "HrOpeningBalanceEndpoint",
    "HrOverviewEndpoint",
    "HrPeriodApproveEndpoint",
    "HrPeriodDaySettleEndpoint",
    "HrPeriodDaysEndpoint",
    "HrPeriodDetailEndpoint",
    "HrPeriodExportEndpoint",
    "HrPeriodListEndpoint",
    "HrPeriodLockEndpoint",
    "HrPeriodRecomputeEndpoint",
    "HrWorklogDetailEndpoint",
    "HrPeriodReopenEndpoint",
    "HrPeriodSubmitEndpoint",
    "HrRateCardEndpoint",
    "HrStatementEndpoint",
    "HrAttendanceDayEndpoint",
    "HrTimeEntryEndpoint",
    "HrWorkScheduleEndpoint",
    "HrSetupEndpoint",
    "HrWorkspaceConfigEndpoint",
]
