# Generated by Django 5.2.15 on 2026-08-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrperiodday',
            name='balance_consumed_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hrperiodday',
            name='leave_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
