# Generated by Django 5.2.15 on 2026-08-28 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_merge_20260811_0947'),
        ('hr', '0002_hrperiodday_balance_consumed_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hrabsencetype',
            name='precedence',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hrperiod',
            name='balance_consumed_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrabsence',
            name='absence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='absences', to='hr.hrabsencetype'),
        ),
        migrations.AlterField(
            model_name='hrinvoicedocument',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_documents', to='hr.hrperiod'),
        ),
        migrations.AlterField(
            model_name='hrinvoicedocument',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_documents', to='hr.hremploymentprofile'),
        ),
        migrations.AddConstraint(
            model_name='hrholidaycalendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('workspace',), name='unique_hr_default_holiday_calendar'),
        ),
    ]
