# Generated by Django 5.2.15 on 2026-08-28 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_merge_20260811_0947'),
        ('hr', '0003_hrabsencetype_precedence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hremploymentprofile',
            name='unique_hr_profile_per_member',
        ),
        migrations.AddConstraint(
            model_name='hremploymentprofile',
            constraint=models.UniqueConstraint(fields=('member',), name='unique_hr_profile_per_member'),
        ),
    ]
