# Generated by Django 5.2.15 on 2026-09-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_hremploymentprofile_unique_hr_profile_per_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrattendanceday',
            name='work_location',
            field=models.PositiveSmallIntegerField(choices=[(10, "At the employer's premises"), (20, 'Telearbeit'), (30, 'Somewhere else')], default=10),
        ),
    ]
