# Generated by Django 5.2.15 on 2026-09-06 15:30

import django.db.models.deletion
from django.db import migrations, models


def name_the_batch_that_wrote_them(apps, schema_editor):
    """Carry across what the reason text used to say.

    Absences imported before this column existed were recognised by a phrase the
    import left in their reason. Adding the column without reading that phrase
    once would leave every one of them unreachable by the undo meant to find them
    — and unlike the phrase, the column cannot later be edited away.
    """
    HrAbsence = apps.get_model("hr", "HrAbsence")
    HrImportBatch = apps.get_model("hr", "HrImportBatch")

    for batch_id in HrImportBatch.objects.values_list("id", flat=True):
        HrAbsence.objects.filter(reason__contains=f"batch {batch_id}").update(import_batch_id=batch_id)


def forget_again(apps, schema_editor):
    """Nothing to undo: the reason text the column was read from is still there."""


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_attendance_work_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrabsence',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences', to='hr.hrimportbatch'),
        ),
        migrations.RunPython(name_the_batch_that_wrote_them, forget_again),
    ]
